### ISSUE TITLE
"Error response from daemon: network with name lachesis already exists" when running ./start.sh 

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/go-lachesis#360] opened 2019-10-21 03:23 UTC
**Describe the bug**
After running `make` inside the `docker` folder (https://github.com/Fantom-foundation/go-lachesis/tree/scope2#running-the-demo), I ran `./start.sh`. After running that command, I get the following error:

`Error response from daemon: network with name lachesis already exists`
**To Reproduce**
1. `git clone -b scope2 git@github.com:Fantom-foundation/go-lachesis.git`
2. `cd docker`
3. `make`
4. `./start.sh`

**Expected behavior**
A demo network in docker should be spun up.

**Desktop:**
 - OS: Mojave 10.14.6

**Comment by MKong** [comment] 2019-10-21 03:57
Running `./stop.sh` returns `Error: No such object: lachesis-node-1`

**Comment by devintegral3** [comment] 2019-10-21 04:22
We were able to reproduce the error only if:
```
./start.sh
# change N in _params.sh
```

**Comment by devintegral3** [comment] 2019-10-21 04:41
Please erase all the left containers withdocker stop / docker rm

**Comment by quan8** [comment] 2019-10-21 04:45
I can confirm the error Michael has seen.
$docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ ./stop.sh 
Error: No such object: lachesis-node-1

**Comment by devintegral3** [comment] 2019-10-21 04:47
It gets the network name as network name of first lachesis instance. So if you don't have any lachesis instances, then it says that there's no network to stop.

**Comment by devintegral3** [comment] 2019-10-21 05:08
Testing scripts are meant to be used by Lachesis developers, so there're not that nice yet. But pay attention that scope2 contains:
- aBFT consensus algorithm and security
- new p2p protocol
- EVM support
- web3.js support

The next scope is focused on economy and user-related enhancements, so, regarding your issue, we will have to improve in scope3:
- testing scripts
- launching flags
- configs
- console
- API

**Comment by quan8** [comment] 2019-10-21 05:09
The error output was caused by the docker inspect command.
So proposed solution is the redirect the err and then check if NETWORK is empty.

**Comment by devintegral** [comment] 2019-11-07 03:14
Will be fixed with #368 , see https://github.com/sfxdxdev/go-lachesis/commit/4bbde19e1b5e2076dc80d60e4f2e52d1f3d9a8ea#diff-03fc5633d7083d19f945376eccca3b40

**Closed** 2020-01-09 04:38 UTC
Labels: bug
